version: '3'
services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
    - 5432:5432
    volumes:
    - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ broker
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - ./.data/rabbitmq:/var/lib/rabbitmq
  cache:
    image: redis:7.2.0-alpine
    restart: always
    ports:
    - 6379:6379
    command: >
      --requirepass P@ssw0rd
  webapp:
    build: .
    command: webapp --spawn 10
    restart: always
    ports:
    - "5000:5000"
    volumes:
    - "./:/opt/app"
    depends_on:
    - db
    - rabbitmq
    - cache
  keeper:
    build: .
    command: keeper
    restart: always
    depends_on:
    - webapp
  checker:
    build: .
    command: checker
    restart: always
    volumes:
    - "./:/opt/app/"
    depends_on:
    - webapp
  svcmanager:
    build: .
    command: svcmanager
    restart: always
    volumes:
    - "./:/opt/app/"
    depends_on:
    - webapp
  flagrotator:
    build: .
    command: flagrotator
    restart: always
    volumes:
    - "./:/opt/app/"
    depends_on:
    - webapp