- name: Create Caddyfile folder
  file:
    path: "/etc/caddy/caddy.d"
    state: directory
    mode: 0755

- name: Create ssl cert folder
  file:
    path: "/etc/caddy/ssl/{{ domain }}"
    state: directory
    mode: 0755

- name: Copy ssl cert to target system
  copy:
    src: "{{ ssl_cert_file.cert }}"
    dest: "/etc/caddy/ssl/{{ domain }}/cert"
    mode: 0644
  when: not public_ca

- name: Copy ssl key to target system
  copy:
    src: "{{ ssl_cert_file.key }}"
    dest: "/etc/caddy/ssl/{{ domain }}/key"
    mode: 0644
  when: not public_ca

- name: Create config file
  template:
    src: config.j2
    dest: /etc/caddy/caddy.d/{{domain}}

- name: Combine configuration files to Caddyfile
  assemble:
    src: /etc/caddy/caddy.d
    dest: /etc/caddy/Caddyfile

- name: Restart Caddy service
  systemd:
    name: caddy
    state: restarted
