"""Update to testcase_artifact in challenge table

Revision ID: 1f72fddcddc8
Revises: 621240ce0d3f
Create Date: 2024-07-23 22:24:31.620239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f72fddcddc8'
down_revision = '621240ce0d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testcase_checksum', sa.String(), nullable=False))
        batch_op.drop_column('artifact_checksum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artifact_checksum', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('testcase_checksum')

    # ### end Alembic commands ###
