"""remove unique server_id from challenges

Revision ID: 27f278c8e0a0
Revises: f6cf4b0040f6
Create Date: 2023-09-07 22:19:35.955897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f278c8e0a0'
down_revision = 'f6cf4b0040f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_constraint('challenges_server_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_unique_constraint('challenges_server_id_key', ['server_id'])

    # ### end Alembic commands ###
