"""add round and tick on checker

Revision ID: 3dcaba762be0
Revises: b2591bc6e942
Create Date: 2023-08-26 01:07:06.667436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcaba762be0'
down_revision = 'b2591bc6e942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checker_queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tick', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checker_queues', schema=None) as batch_op:
        batch_op.drop_column('tick')
        batch_op.drop_column('round')

    # ### end Alembic commands ###
