"""add chall id to constraint

Revision ID: 434fe8065050
Revises: 27f278c8e0a0
Create Date: 2023-09-08 14:25:15.320869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434fe8065050'
down_revision = '27f278c8e0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_per_ticks', schema=None) as batch_op:
        batch_op.drop_constraint('score_per_ticks_round_tick_team_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['round', 'tick', 'team_id', 'challenge_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_per_ticks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('score_per_ticks_round_tick_team_id_key', ['round', 'tick', 'team_id'])

    # ### end Alembic commands ###
