"""Change credential colname to detail in provmachine

Revision ID: 43b8cf2185bc
Revises: 43e72e6a5fae
Create Date: 2024-07-24 14:43:29.955295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b8cf2185bc'
down_revision = '43e72e6a5fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provision_machine', schema=None) as batch_op:
        batch_op.alter_column("credential", new_column_name="detail")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provision_machine', schema=None) as batch_op:
        batch_op.alter_column("detail", new_column_name="credential")

    # ### end Alembic commands ###
