"""Add secret column in service

Revision ID: 621240ce0d3f
Revises: 4b7374c4f9c9
Create Date: 2024-07-23 00:32:58.679135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621240ce0d3f'
down_revision = '4b7374c4f9c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.String(), nullable=False, server_default="default"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('secret')

    # ### end Alembic commands ###
