"""Support multi flag and add artifact sum

Revision ID: 9f9f857df3fb
Revises: 43b8cf2185bc
Create Date: 2024-07-25 01:01:51.331441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9f857df3fb'
down_revision = '43b8cf2185bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_flag', sa.Integer(), nullable=False, server_default="1"))
        batch_op.add_column(sa.Column('artifact_checksum', sa.String(), nullable=True))
        batch_op.alter_column('testcase_checksum',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('flag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False, server_default="0"))
        batch_op.drop_constraint('flag_team_id_challenge_id_round_tick_key', type_='unique')
        batch_op.create_unique_constraint(None, ['team_id', 'challenge_id', 'round', 'tick', 'order'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('flag_team_id_challenge_id_round_tick_key', ['team_id', 'challenge_id', 'round', 'tick'])
        batch_op.drop_column('order')

    with op.batch_alter_table('challenge', schema=None) as batch_op:
        batch_op.alter_column('testcase_checksum',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('artifact_checksum')
        batch_op.drop_column('num_flag')

    # ### end Alembic commands ###
