"""enrich submission table and add indexing

Revision ID: b2591bc6e942
Revises: c54adf368a31
Create Date: 2023-08-12 19:41:24.371447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2591bc6e942'
down_revision = 'c54adf368a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flags_challenge_id'), ['challenge_id'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_id', sa.Integer(), nullable=True))
        batch_op.create_index('team_id', ['flag_id', 'verdict'], unique=False)
        batch_op.create_foreign_key(None, 'flags', ['flag_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('team_id')
        batch_op.drop_column('flag_id')

    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flags_challenge_id'))

    # ### end Alembic commands ###
