"""multi flag support

Revision ID: b90c23888c3f
Revises: 434fe8065050
Create Date: 2023-10-22 21:05:19.383828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90c23888c3f'
down_revision = '434fe8065050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_flag', sa.Integer(), nullable=True))

    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subid', sa.Integer(), nullable=True))
        batch_op.drop_constraint('flags_team_id_challenge_id_round_tick_key', type_='unique')
        batch_op.create_unique_constraint(None, ['team_id', 'challenge_id', 'subid', 'round', 'tick'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('flags_team_id_challenge_id_round_tick_key', ['team_id', 'challenge_id', 'round', 'tick'])
        batch_op.drop_column('subid')

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('num_flag')

    # ### end Alembic commands ###
