"""empty message

Revision ID: c54adf368a31
Revises: 
Create Date: 2023-08-09 01:36:06.866339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54adf368a31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configs_key'), ['key'], unique=True)

    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=50), nullable=True),
    sa.Column('sshport', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('auth_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host')
    )
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('num_expose', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('server_host', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('server_host', sa.String(), nullable=True),
    sa.Column('secret', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_email'), ['email'], unique=True)

    op.create_table('challenge_releases',
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('round', 'challenge_id')
    )
    op.create_table('checker_queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('QUEUE', 'PROCESS', 'FAULTY', 'VALID', name='checkerverdict'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('tick', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'challenge_id', 'round', 'tick')
    )
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flags_value'), ['value'], unique=False)

    op.create_table('score_per_ticks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('tick', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('attack_score', sa.Double(), nullable=True),
    sa.Column('defense_score', sa.Double(), nullable=True),
    sa.Column('sla', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round', 'tick', 'team_id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('team_id', 'challenge_id', 'order')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index('service_idx', ['team_id', 'challenge_id'], unique=False)

    op.create_table('solves',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'challenge_id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('tick', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('verdict', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_value'))

    op.drop_table('submissions')
    op.drop_table('solves')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index('service_idx')

    op.drop_table('services')
    op.drop_table('score_per_ticks')
    with op.batch_alter_table('flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flags_value'))

    op.drop_table('flags')
    op.drop_table('checker_queues')
    op.drop_table('challenge_releases')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_email'))

    op.drop_table('teams')
    op.drop_table('challenges')
    op.drop_table('servers')
    with op.batch_alter_table('configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configs_key'))

    op.drop_table('configs')
    # ### end Alembic commands ###
