"""add message for checker

Revision ID: f6cf4b0040f6
Revises: e34cfe47b859
Create Date: 2023-09-01 02:35:47.043589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cf4b0040f6'
down_revision = 'e34cfe47b859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checker_queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checker_queues', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
