- name: Clone frontend git repository
  git:
    repo: "{{ repository.frontend }}"
    dest: "/opt/ailurus-frontend"
    version: "{{ repository.frontend_branch | default('HEAD') }}"

- name: Generating environment file
  template:
    src: "env-file.j2"
    dest: /opt/ailurus-frontend/.env

- name: Build frontend Docker image
  docker_image:
    name: ailurus-frontend
    source: build
    build:
      path: /opt/ailurus-frontend
    state: present
    force_source: true